version: '3.3'
services:
  backend:
    build: ./Backend
    ports:
      - "9005:8000"
    depends_on:
      - db
  frontend:
    build: ./Front
    ports:
      - "9007:8080"
    depends_on:
      - backend

  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
