# Generated by Django 4.2 on 2023-04-15 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('fechaInicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fechaFin', models.DateField(verbose_name='Fecha de fin')),
                ('duracion', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoPat', models.CharField(max_length=50)),
                ('apellidoMat', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=500, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(default=0)),
                ('comentario', models.TextField()),
                ('actividades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siglas', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fechaFin', models.DateField(verbose_name='Fecha de fin')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoPat', models.CharField(max_length=50)),
                ('apellidoMat', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=500, verbose_name='Contraseña')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('contenido', models.FileField(upload_to='data_base/JSONdoc/')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.tema')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('uf', models.CharField(max_length=15)),
                ('cupo', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('actividad', models.ManyToManyField(to='data_base.actividad')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.periodo')),
                ('profesor', models.ManyToManyField(to='data_base.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoPat', models.CharField(max_length=50)),
                ('apellidoMat', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=500, verbose_name='Contraseña')),
                ('calificacion', models.ManyToManyField(through='data_base.Calificacion', to='data_base.actividad')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.carrera')),
            ],
        ),
        migrations.AddField(
            model_name='calificacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='data_base.estudiante'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='pregunta',
            field=models.ManyToManyField(to='data_base.pregunta'),
        ),
    ]
