# Generated by Django 4.2 on 2023-04-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siglas', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=256),
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='profesor',
        ),
        migrations.AddField(
            model_name='grupo',
            name='profesor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='data_base.profesor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grupo',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.uf'),
        ),
    ]
