# Generated by Django 4.2 on 2023-04-26 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0002_uf_carrera_nombre_alter_departamento_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dificultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RenameField(
            model_name='calificacion',
            old_name='calificacion',
            new_name='ponderacion',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='actividades',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='actividad',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='puntosTotal',
            field=models.IntegerField(default=0, verbose_name='Puntos totales'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='estado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='profesor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='data_base.profesor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipoP',
            field=models.BooleanField(default=0, verbose_name='tipo de pregunta | Abierta 0 | Cerrada 1'),
        ),
        migrations.AddField(
            model_name='tema',
            name='nombre',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tema',
            name='tipo',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.estudiante'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellidoMat',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellidoPat',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='especialidad',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
        migrations.AddField(
            model_name='estudiantegrupo',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.estudiante'),
        ),
        migrations.AddField(
            model_name='estudiantegrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.grupo'),
        ),
        migrations.AddField(
            model_name='actividadpregunta',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.actividad'),
        ),
        migrations.AddField(
            model_name='actividadpregunta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.pregunta'),
        ),
        migrations.AddField(
            model_name='actividadgrupo',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.actividad'),
        ),
        migrations.AddField(
            model_name='actividadgrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.grupo'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='actividad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='data_base.actividadpregunta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='dificultad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='data_base.dificultad'),
            preserve_default=False,
        ),
    ]
