# Generated by Django 4.2 on 2023-05-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0003_actividadgrupo_actividadpregunta_dificultad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='tipo',
            field=models.TextField(verbose_name='subtema'),
        ),
    ]
