<<<<<<< HEAD
# Generated by Django 4.2 on 2023-05-28 22:19
=======
# Generated by Django 4.2.1 on 2023-05-22 05:08
>>>>>>> f37f7048db3e8dd90cf093693308d729289562db

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0003_actividadgrupo_actividadpregunta_dificultad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='tipo',
            field=models.TextField(verbose_name='subtema'),
        ),
    ]
