# Generated by Django 4.2.1 on 2023-06-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0005_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
