# Generated by Django 4.2.1 on 2023-05-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0005_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AddField(
            model_name='profesor',
            name='nomina',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellidoMat',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellidoPat',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='contrasena',
            field=models.CharField(blank=True, max_length=500, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='matricula',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='titulo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellidoMat',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellidoPat',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='contrasena',
            field=models.CharField(blank=True, max_length=500, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='especialidad',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
